//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int Id { get; set; }
        public string TaskName { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> IsParent { get; set; }
        public Nullable<int> ParentTaskId { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> ContactId { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
